### ISSUE TITLE
stack build complains

### ISSUE THREAD

**Issue by Gurkenglas** [lukexi/rumpus#9]
I ran the new script, it worked, then did stack build, and got [terminalsession.txt](https://github.com/lukexi/rumpus/files/418194/terminalsession.txt). Since the top fell off the scrollback, I piped stderr into a log, but since something was already there, I deleted that and did it again, and then it turned out the contents were different, so I'm pasting both. [log.txt](https://github.com/lukexi/rumpus/files/418196/log.txt) Also here's the [logs.zip](https://github.com/lukexi/rumpus/files/418200/logs.zip) from .stack-work, there's also at least some warnings in there.

Edit: Oh hey, opening it in sublime rather than notepad inserts line breaks at enough points to make it readable! Up next, my stream of research as a logfile for you, Nothing object-level helpful I think. Hmm, missing a system package. I did the pacman install step from your build guide already, I think, before I tried the nonworking .sh, but lets do it again and see what happens. msys says "bash: pacman: command not found". Huh that might be something to do with msys, after installing, saying something with links or something like that changing (and indeed the start menu msys starter thing doesnt work). Worked before I did the .sh, hmm. Lets google "bash: pacman: command not found" windows (some other fruitless searches omitted). Aha, "add C:\msys64\usr\bin to path". Restart msys and works. [msyslog.txt](https://github.com/lukexi/rumpus/files/418232/msyslog.txt). stack build still fails the same way.

Edit2: [This IRC discussion](http://ircbrowse.net/browse/haskell?id=23220929&timestamp=1471272537#t1471272537) makes it sound like those pacman installs should be doable by the stack build file? Also is this the correct channel for this problem? Cause I just noticed we're supposed to send build problems per email... ehh this is surely fine.

**Comment by lukexi** [comment]
Hi Gurkenglas,

Looks like the error is probably due to the failed recursive checkout you had last time? It's failing to find `m_pd.h` which should be in `pd-hs/libpd/pure-data/src`

Yes, this is perfectly fine for issues! I'll update the README : )

**Comment by lukexi** [comment]
(so running `git pull && git submodule update --init --recursive` in `pd-hs` should hopefully get it going)

**Comment by Gurkenglas** [comment]
```
C:\Users\Gurkenglas\Documents\GitHub\rumpus\pd-hs>git pull && git submodule update --init --recursive 2> log.txt
Already up-to-date.

C:\Users\Gurkenglas\Documents\GitHub\rumpus\pd-hs>
```

And the log.txt:

```
Cloning into 'pure-data'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:lukexi/pure-data' into submodule path 'pure-data' failed
Failed to recurse into submodule path 'libpd'

```

**Comment by lukexi** [comment]
OK, switched my libpd repo to https too...
(although now that I think of it I've cloned all this on other computers than my own without trouble before, so I'm not sure why you're having public key issues - do you have your public keys set up with github?)

**Comment by Gurkenglas** [comment]
```
C:\Users\Gurkenglas\Documents\GitHub\rumpus\pd-hs>git pull && git submodule update --init --recursive
Already up-to-date.
Cloning into 'pure-data'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:lukexi/pure-data' into submodule path 'pure-data' failed
Failed to recurse into submodule path 'libpd'
```

Maybe you forgot to push?

**Comment by Gurkenglas** [comment]
I dont think I explicitly set up github "keys" at any point.

Here's some more public-key error throwers when I try doing the .sh thing into a fresh folder:

```
`Cloning into 'gl-pal'...
remote: Counting objects: 1057, done.
remote: Total 1057 (delta 0), reused 0 (delta 0), pack-reused 1057
Receiving objects: 100% (1057/1057), 134.19 KiB | 0 bytes/s, done.
Resolving deltas: 100% (533/533), done.
Checking connectivity... done.
Cloning into 'bullet-mini'...
remote: Counting objects: 748, done.
remote: Total 748 (delta 0), reused 0 (delta 0), pack-reused 748
Receiving objects: 100% (748/748), 480.37 KiB | 353.00 KiB/s, done.
Resolving deltas: 100% (420/420), done.
Checking connectivity... done.
Submodule 'bullet3' (git@github.com:bulletphysics/bullet3.git) registered for pa                                                                                                                                                                                               th 'bullet3'
Cloning into 'bullet3'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:bulletphysics/bullet3.git' into submodule path 'bullet3                                                                                                                                                                                               ' failed
Cloning into 'vr-pal'...
remote: Counting objects: 896, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 896 (delta 0), reused 0 (delta 0), pack-reused 883
Receiving objects: 100% (896/896), 146.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (424/424), done.
Checking connectivity... done.
Cloning into 'glfw-pal'...
remote: Counting objects: 318, done.
0), reused 0 (delta 0), pack-reused 318
Receiving objects: 100% (318/318), 28.84 KiB | 0 bytes/s, done.
Resolving deltas: 100% (90/90), done.
Checking connectivity... done.
Cloning into 'halive'...
remote: Counting objects: 622, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 622 (delta 0), reused 0 (delta 0), pack-reused 617eceiving objeK
Receiving objects: 100% (622/622), 127.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (356/356), done.
Checking connectivity... done.
Cloning into 'animation-pal'...
remote: Counting objects: 154, done.
remote: Compressing objects: 100% (64/64), done.
remote: TotalRec 154eiving ob (delta 76), reused 154 jects: (delta  51% (776), p                                                                                                                                                                                               ack-reused9/15 0
Receiving objects: 100% (154/154), 23.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (76/76), done.
Checking connectivity... done.
Cloning into 'linear-extra'...
remote: Counting objects: 183, done.
), reused 0 (delta 0), pack-reused 183
Receiving objects: 100% (183/183), 17.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (81/81), done.
Checking connectivity... done.
Cloning into 'lens-extra'...
remote: Counting objects: 40, done.
remote: Total 40 (delta 0), reused 0 (delta 0), pack-reused 40
Unpacking objects: 100% (40/40), done.
Checking connectivity... done.
Cloning into 'openvr-hs'...
remote: Counting objects: 562, done.
remote: Total 562 (delta 0), reused 0 (delta 0), pack-reused 562
Receiving objects: 100% (562/562), 256.23 KiB | 332.00 KiB/s, done.
Resolving deltas: 100% (251/251), done.
Checking connectivity... done.
Submodule 'openvr' (git@github.com:ValveSoftware/openvr.git) registered for path 'openvr'
Cloning into 'openvr'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:ValveSoftware/openvr.git' into submodule path 'openvr' failed
Cloning into 'pd-hs'...
remote: Counting objects: 568, done.
remote: Total 568 (delta 0), reused 0 (delta 0), pack-reused 568
Receiving objects: 100% (568/568), 1.68 MiB | 421.00 KiB/s, done.
Resolving deltas: 100% (304/304), done.
Checking connectivity... done.
Submodule 'libpd' (https://github.com/lukexi/libpd) registered for path 'libpd'
Cloning into 'libpd'...
remote: Counting objects: 5028, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5028 (delta 0), reused 0 (delta 0), pack-reused 5025
Receiving objects: 100% (5028/5028), 7.51 MiB | 430.00 KiB/s, done.
Resolving deltas: 100% (2457/2457), done.
Checking connectivity... done.
Submodule path 'libpd': checked out '04fcd43f9b5323daca19dd97cf4c02a9009538bc'
Submodule 'jni/opensl_stream' (git://github.com/nettoyeurny/opensl_stream.git) registered for path 'jni/opensl_stream'
Submodule 'pure-data' (git@github.com:lukexi/pure-data) registered for path 'pure-data'
Cloning into 'jni/opensl_stream'...
remote: Counting objects: 51, done.
remote: Total 51 (delta 0), reused 0 (delta 0), pack-reused 51
Receiving objects: 100% (51/51), 12.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (28/28), done.
Checking connectivity... done.
Submodule path 'libpd/jni/opensl_stream': checked out '5f3930698569754c519f5b3e4cc7691223bc99a8'
Cloning into 'pure-data'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:lukexi/pure-data' into submodule path 'pure-data' failed
Failed to recurse into submodule path 'libpd'
Cloning into 'bindings-GLFW'...
remote: Counting objects: 517, done.
remote: Total 517 (delta 0), reused 0 (delta 0), pack-Receireuvised 517ng
Receiving objects: 100% (517/517), 740.25 KiB | 403.00 KiB/s, done.
Resolving deltas: 100% (285/285), done.
Checking connectivity... done.
Cloning into 'freetype-gl-mini'...
remote: Counting objects: 934, done.
remote: Total 934 (delta 0), reused 0 (delta 0), pack-reused 934
Receiving objects: 100% (934/934), 149.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (504/504), done.
Checking connectivity... done.
Submodule 'freetype-gl' (https://github.com/rougier/freetype-gl) registered for path 'freetype-gl'
Cloning into 'freetype-gl'...
remote: Counting objects: 2651, done.
Receiving objects:  19% (526/2651), 3.44 MiB | 432.00 KiB/s
`
```

The end got chopped off because the window closes when the script is done.

Take a look at https://github.com/search?l=&q=git%40+user%3Alukexi&ref=advsearch&type=Code&utf8=%E2%9C%93 ?

**Comment by lukexi** [comment]
I updated more of the repos - try a `git submodule sync` to have them pull in the new URLs.
And this should fix the problem overall:
https://help.github.com/articles/generating-an-ssh-key/

**Comment by lukexi** [comment]
I switched the rumpus repo to submodules which should hopefully make life easier down the road!
`git submodule update --init --recursive` should pull them in.

**Comment by lukexi** [comment]
I realized I can't push to GitHub with them set as HTTPS, so you'll have to do the SSH key thing : )

**Comment by Gurkenglas** [comment]
Edit: Nevermind on this one, mistyped the passphrase. Let me get rid of it.

**Comment by lukexi** [comment]
You can use ssh-agent so you only have to enter it when you reboot your computer : )
https://help.github.com/articles/working-with-ssh-key-passphrases/#auto-launching-ssh-agent-on-msysgit

**Comment by Gurkenglas** [comment]
`stack build` works now.
(
But:

```
Gurkenglas@Gurkenglas-PC  /c/Users/Gurkenglas/Documents/GitHub/rumpus/rumpus
$ stack exec rumpus
C:/Users/Gurkenglas/AppData/Roaming/local/bin/stack.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

The build guide says

```
Rumpus requires GHC 8. If you have trouble running Rumpus after building, please use this preview build of GHC 8.0.2 which resolves a linker issue. https://github.com/lukexi/ghc/releases/download/8.0.1.1/ghc-8.0.1-x86_64-unknown-mingw32.tar.xz"
```

, but how do I make stack use that? Nobody answered on the IRC when I asked.
)

**Comment by lukexi** [comment]
Yahoo!!

Hm according to the stack manual, it will use the system GHC as long as it is in the PATH (i.e. `which ghc` gives `/usr/local/ghc/bin/ghc` - which I achieve by just copying ghc there manually and adding `/usr/local/ghc` to my `.profile` as documented in https://gist.github.com/lukexi/e634067f1d7e3a629988

The manual claims it defaults to `true`, but you can try adding to `$APPDATA/stack/config.yaml`
`system-ghc: true`
(via https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md)
if the above still doesn't work!

**Comment by Gurkenglas** [comment]
Before copying your executable, msys2 does not know the ghc command. After: lpaste.net/1862648520805187584 (msys2 session)
global config.yaml after the first stack exec -- ghc --version:

```
extra-lib-dirs: ["D:\\Haskell"]

templates:
  params:
    author-email: gurkenglas@hotmail.de
    author-name: Gurkenglas
    category: library
    copyright: (c) 2016-2016 Gurkenglas
    github-username: Gurkenglas

system-ghc: true
```

**Comment by lukexi** [comment]
The key line is
`Run from outside a project, using implicit global project config`
which is what you get when you run `stack` from outside of a stack project
(the global project config is in `$APPDATA/stack/global-project/stack.yaml`)

If you run it from within the `rumpus` directory you should get a different result since it will use rumpus's `stack.yaml` instead which specifies GHC 8.

**Comment by Gurkenglas** [comment]
Yea, that gives 8.0.1, whether I have that new ghc or not. So what do I do now? That error's still there. Copying the config.yaml into the rumpus folder so it'll also count for that doesn't even make it build anew, and I didn't expect it to because that config looks global and you don't have it in the repository.

(Note that some of the pasted msys2 session output is only visible once you scroll to the right.)

**Comment by lukexi** [comment]
Oh 8.0.1 is right! The version I compiled still reports as 8.0.1 since it is just that with one of the patches from 8.0.2. Is that the error you mean?

**Comment by Gurkenglas** [comment]
No, I mean at the end:

```
$ stack exec rumpus
C:/Users/Gurkenglas/AppData/Roaming/local/bin/stack.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

(The right part of that is transposed to the right in the lpaste.)

**Comment by lukexi** [comment]
I missed that sorry! Hmm that is a new one... usually library errors occur during stack build. Did you run `scripts/copyLibsWin.sh`? You can also try `stack clean && stack build`, maybe something about switching out the submodules confused things?

The list of needed libraries is:

```
libfreetype-6.dll
libpd.dll
libwinpthread-1.dll
OpenAL32.dll
openvr_api.dll
libstdc++-6.dll
libbz2-1.dll
libharfbuzz-0.dll
zlib1.dll
libpng16-16.dll
libgcc_s_seh-1.dll
libglib-2.0-0.dll
libintl-8.dll
libiconv-2.dll
/mingw64/x86_64-w64-mingw32/lib/libmingw32.a
/mingw64/x86_64-w64-mingw32/lib/libmingwex.a
```

(which I have to copy in `scripts/rumpus-release.sh` to get a standalone executable)
You could also try running that script, and then double-clicking the rumpus.exe in `.release` from Windows to see if it gives you more information as to what's missing.

**Comment by Gurkenglas** [comment]
I did run `scripts/copyLibsWin.sh`. (Retried now too.) `stack clean && stack build` works, but doesn't change anything. Running that sh:

[logrelease.txt](https://github.com/lukexi/rumpus/files/428076/logrelease.txt)

And then:

```
$ /c/Users/Gurkenglas/Documents/GitHub/rumpus/.release/rumpus.exe
C:/Users/Gurkenglas/Documents/GitHub/rumpus/.release/rumpus.exe: error while loading shared libraries: libpd.dll: cannot open shared object file: No such file or directory
```

So I need to install Leksah or something?

(Want a TeamViewer session?)

**Comment by lukexi** [comment]
Hopping on IRC now : )

**Comment by lukexi** [comment]
Noting for posterity - we figured out that this was due to a bad MSYS2 installation, and fixed by reinstalling it according to https://gist.github.com/lukexi/e634067f1d7e3a629988
